blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/{{OWNER}}/{{PROJECT_NAME}}/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
